
package com.jasperwireless.api.ws.schema;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "AccountPortType", targetNamespace = "http://api.jasperwireless.com/ws/schema")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AccountPortType {


    /**
     * 
     * @param body
     * @return
     *     returns com.jasperwireless.api.ws.schema.GetAccountsResponse
     */
    @WebMethod(operationName = "GetAccounts", action = "http://api.jasperwireless.com/ws/service/account/GetAccounts")
    @WebResult(name = "GetAccountsResponse", targetNamespace = "http://api.jasperwireless.com/ws/schema", partName = "body")
    public GetAccountsResponse getAccounts(
        @WebParam(name = "GetAccountsRequest", targetNamespace = "http://api.jasperwireless.com/ws/schema", partName = "body")
        GetAccountsRequest body);

    /**
     * 
     * @param body
     * @return
     *     returns com.jasperwireless.api.ws.schema.GetAccountDetailsResponse
     */
    @WebMethod(operationName = "GetAccountDetails", action = "http://api.jasperwireless.com/ws/service/account/GetAccountDetails")
    @WebResult(name = "GetAccountDetailsResponse", targetNamespace = "http://api.jasperwireless.com/ws/schema", partName = "body")
    public GetAccountDetailsResponse getAccountDetails(
        @WebParam(name = "GetAccountDetailsRequest", targetNamespace = "http://api.jasperwireless.com/ws/schema", partName = "body")
        GetAccountDetailsRequest body);

    /**
     * 
     * @param body
     * @return
     *     returns com.jasperwireless.api.ws.schema.GetAccountDetailsTelkomselLBSResponse
     */
    @WebMethod(operationName = "GetAccountDetailsTelkomselLBS", action = "http://api.jasperwireless.com/ws/service/account/GetAccountDetailsTelkomselLBS")
    @WebResult(name = "GetAccountDetailsTelkomselLBSResponse", targetNamespace = "http://api.jasperwireless.com/ws/schema", partName = "body")
    public GetAccountDetailsTelkomselLBSResponse getAccountDetailsTelkomselLBS(
        @WebParam(name = "GetAccountDetailsTelkomselLBSRequest", targetNamespace = "http://api.jasperwireless.com/ws/schema", partName = "body")
        GetAccountDetailsTelkomselLBSRequest body);

    /**
     * 
     * @param body
     * @return
     *     returns com.jasperwireless.api.ws.schema.CreateAccountResponse
     */
    @WebMethod(operationName = "CreateAccount", action = "http://api.jasperwireless.com/ws/service/account/CreateAccount")
    @WebResult(name = "CreateAccountResponse", targetNamespace = "http://api.jasperwireless.com/ws/schema", partName = "body")
    public CreateAccountResponse createAccount(
        @WebParam(name = "CreateAccountRequest", targetNamespace = "http://api.jasperwireless.com/ws/schema", partName = "body")
        CreateAccountRequest body);

    /**
     * 
     * @param body
     * @return
     *     returns com.jasperwireless.api.ws.schema.GetAccountIdByAcctNameResponse
     */
    @WebMethod(operationName = "GetAccountIdByAcctName", action = "http://api.jasperwireless.com/ws/service/account/GetAccountIdByAcctName")
    @WebResult(name = "GetAccountIdByAcctNameResponse", targetNamespace = "http://api.jasperwireless.com/ws/schema", partName = "body")
    public GetAccountIdByAcctNameResponse getAccountIdByAcctName(
        @WebParam(name = "GetAccountIdByAcctNameRequest", targetNamespace = "http://api.jasperwireless.com/ws/schema", partName = "body")
        GetAccountIdByAcctNameRequest body);

    /**
     * 
     * @param body
     * @return
     *     returns com.jasperwireless.api.ws.schema.GetAccountIdByOpAcctIdResponse
     */
    @WebMethod(operationName = "GetAccountIdByOpAcctId", action = "http://api.jasperwireless.com/ws/service/account/GetAccountIdByOpAcctId")
    @WebResult(name = "GetAccountIdByOpAcctIdResponse", targetNamespace = "http://api.jasperwireless.com/ws/schema", partName = "body")
    public GetAccountIdByOpAcctIdResponse getAccountIdByOpAcctId(
        @WebParam(name = "GetAccountIdByOpAcctIdRequest", targetNamespace = "http://api.jasperwireless.com/ws/schema", partName = "body")
        GetAccountIdByOpAcctIdRequest body);

    /**
     * 
     * @param body
     * @return
     *     returns com.jasperwireless.api.ws.schema.GetAccountPeerStatusResponse
     */
    @WebMethod(operationName = "GetAccountPeerStatus", action = "http://api.jasperwireless.com/ws/service/account/GetAccountPeerStatus")
    @WebResult(name = "GetAccountPeerStatusResponse", targetNamespace = "http://api.jasperwireless.com/ws/schema", partName = "body")
    public GetAccountPeerStatusResponse getAccountPeerStatus(
        @WebParam(name = "GetAccountPeerStatusRequest", targetNamespace = "http://api.jasperwireless.com/ws/schema", partName = "body")
        GetAccountPeerStatusRequest body);

    /**
     * 
     * @param body
     * @return
     *     returns com.jasperwireless.api.ws.schema.SetAccountPeerStatusResponse
     */
    @WebMethod(operationName = "SetAccountPeerStatus", action = "http://api.jasperwireless.com/ws/service/account/SetAccountPeerStatus")
    @WebResult(name = "SetAccountPeerStatusResponse", targetNamespace = "http://api.jasperwireless.com/ws/schema", partName = "body")
    public SetAccountPeerStatusResponse setAccountPeerStatus(
        @WebParam(name = "SetAccountPeerStatusRequest", targetNamespace = "http://api.jasperwireless.com/ws/schema", partName = "body")
        SetAccountPeerStatusRequest body);

    /**
     * 
     * @param body
     * @return
     *     returns com.jasperwireless.api.ws.schema.EditAccountResponse
     */
    @WebMethod(operationName = "EditAccount", action = "http://api.jasperwireless.com/ws/service/account/EditAccount")
    @WebResult(name = "EditAccountResponse", targetNamespace = "http://api.jasperwireless.com/ws/schema", partName = "body")
    public EditAccountResponse editAccount(
        @WebParam(name = "EditAccountRequest", targetNamespace = "http://api.jasperwireless.com/ws/schema", partName = "body")
        EditAccountRequest body);

}
