
package com.jasperwireless.api.ws.schema;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 *
 */
@WebServiceClient(name = "AddRoutableMSISDNService", targetNamespace = "http://api.jasperwireless.com/ws/schema", wsdlLocation = "http://api.jasperwireless.com/ws/schema/AddRoutableMSISDN.wsdl")
public class AddRoutableMSISDNService
    extends Service
{

    private final static URL ADDROUTABLEMSISDNSERVICE_WSDL_LOCATION;
    private final static WebServiceException ADDROUTABLEMSISDNSERVICE_EXCEPTION;
    private final static QName ADDROUTABLEMSISDNSERVICE_QNAME = new QName("http://api.jasperwireless.com/ws/schema", "AddRoutableMSISDNService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://api.jasperwireless.com/ws/schema/AddRoutableMSISDN.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ADDROUTABLEMSISDNSERVICE_WSDL_LOCATION = url;
        ADDROUTABLEMSISDNSERVICE_EXCEPTION = e;
    }

    public AddRoutableMSISDNService() {
        super(__getWsdlLocation(), ADDROUTABLEMSISDNSERVICE_QNAME);
    }

    public AddRoutableMSISDNService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ADDROUTABLEMSISDNSERVICE_QNAME, features);
    }

    public AddRoutableMSISDNService(URL wsdlLocation) {
        super(wsdlLocation, ADDROUTABLEMSISDNSERVICE_QNAME);
    }

    public AddRoutableMSISDNService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ADDROUTABLEMSISDNSERVICE_QNAME, features);
    }

    public AddRoutableMSISDNService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AddRoutableMSISDNService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns AddRoutableMSISDNPortType
     */
    @WebEndpoint(name = "AddRoutableMSISDNPort")
    public AddRoutableMSISDNPortType getAddRoutableMSISDNPort() {
        return super.getPort(new QName("http://api.jasperwireless.com/ws/schema", "AddRoutableMSISDNPort"), AddRoutableMSISDNPortType.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AddRoutableMSISDNPortType
     */
    @WebEndpoint(name = "AddRoutableMSISDNPort")
    public AddRoutableMSISDNPortType getAddRoutableMSISDNPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://api.jasperwireless.com/ws/schema", "AddRoutableMSISDNPort"), AddRoutableMSISDNPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ADDROUTABLEMSISDNSERVICE_EXCEPTION!= null) {
            throw ADDROUTABLEMSISDNSERVICE_EXCEPTION;
        }
        return ADDROUTABLEMSISDNSERVICE_WSDL_LOCATION;
    }

}
