
package com.jasperwireless.api.ws.schema;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AlertService", targetNamespace = "http://api.jasperwireless.com/ws/schema", wsdlLocation = "file:/Users/calvernaz/sandbox/github-modules/jasperwireless-api/src/main/resources/Alert.wsdl")
public class AlertService
    extends Service
{

    private final static URL ALERTSERVICE_WSDL_LOCATION;
    private final static WebServiceException ALERTSERVICE_EXCEPTION;
    private final static QName ALERTSERVICE_QNAME = new QName("http://api.jasperwireless.com/ws/schema", "AlertService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/Users/calvernaz/sandbox/github-modules/jasperwireless-api/src/main/resources/Alert.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ALERTSERVICE_WSDL_LOCATION = url;
        ALERTSERVICE_EXCEPTION = e;
    }

    public AlertService() {
        super(__getWsdlLocation(), ALERTSERVICE_QNAME);
    }

    public AlertService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ALERTSERVICE_QNAME, features);
    }

    public AlertService(URL wsdlLocation) {
        super(wsdlLocation, ALERTSERVICE_QNAME);
    }

    public AlertService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ALERTSERVICE_QNAME, features);
    }

    public AlertService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AlertService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns AlertPortType
     */
    @WebEndpoint(name = "AlertPort")
    public AlertPortType getAlertPort() {
        return super.getPort(new QName("http://api.jasperwireless.com/ws/schema", "AlertPort"), AlertPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AlertPortType
     */
    @WebEndpoint(name = "AlertPort")
    public AlertPortType getAlertPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://api.jasperwireless.com/ws/schema", "AlertPort"), AlertPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ALERTSERVICE_EXCEPTION!= null) {
            throw ALERTSERVICE_EXCEPTION;
        }
        return ALERTSERVICE_WSDL_LOCATION;
    }

}
