
package com.jasperwireless.api.ws.schema;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "AlertPortType", targetNamespace = "http://api.jasperwireless.com/ws/schema")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AlertPortType {


    /**
     * 
     * @param body
     * @return
     *     returns com.jasperwireless.api.ws.schema.GetAlertsResponse
     */
    @WebMethod(operationName = "GetAlerts", action = "http://api.jasperwireless.com/ws/service/alert/GetAlerts")
    @WebResult(name = "GetAlertsResponse", targetNamespace = "http://api.jasperwireless.com/ws/schema", partName = "body")
    public GetAlertsResponse getAlerts(
        @WebParam(name = "GetAlertsRequest", targetNamespace = "http://api.jasperwireless.com/ws/schema", partName = "body")
        GetAlertsRequest body);

    /**
     * 
     * @param body
     * @return
     *     returns com.jasperwireless.api.ws.schema.GetAlertDetailsResponse
     */
    @WebMethod(operationName = "GetAlertDetails", action = "http://api.jasperwireless.com/ws/service/alert/GetAlertDetails")
    @WebResult(name = "GetAlertDetailsResponse", targetNamespace = "http://api.jasperwireless.com/ws/schema", partName = "body")
    public GetAlertDetailsResponse getAlertDetails(
        @WebParam(name = "GetAlertDetailsRequest", targetNamespace = "http://api.jasperwireless.com/ws/schema", partName = "body")
        GetAlertDetailsRequest body);

}
