
package com.jasperwireless.api.ws.schema;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BillingPortType", targetNamespace = "http://api.jasperwireless.com/ws/schema")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BillingPortType {


    /**
     * 
     * @param body
     * @return
     *     returns com.jasperwireless.api.ws.schema.GetTerminalUsageResponse
     */
    @WebMethod(operationName = "GetTerminalUsage", action = "http://api.jasperwireless.com/ws/service/billing/GetTerminalUsage")
    @WebResult(name = "GetTerminalUsageResponse", targetNamespace = "http://api.jasperwireless.com/ws/schema", partName = "body")
    public GetTerminalUsageResponse getTerminalUsage(
        @WebParam(name = "GetTerminalUsageRequest", targetNamespace = "http://api.jasperwireless.com/ws/schema", partName = "body")
        GetTerminalUsageRequest body);

    /**
     * 
     * @param body
     * @return
     *     returns com.jasperwireless.api.ws.schema.GetInvoiceResponse
     */
    @WebMethod(operationName = "GetInvoice", action = "http://api.jasperwireless.com/ws/service/billing/GetInvoice")
    @WebResult(name = "GetInvoiceResponse", targetNamespace = "http://api.jasperwireless.com/ws/schema", partName = "body")
    public GetInvoiceResponse getInvoice(
        @WebParam(name = "GetInvoiceRequest", targetNamespace = "http://api.jasperwireless.com/ws/schema", partName = "body")
        GetInvoiceRequest body);

    /**
     * 
     * @param body
     * @return
     *     returns com.jasperwireless.api.ws.schema.GetTerminalUsageDataDetailsResponse
     */
    @WebMethod(operationName = "GetTerminalUsageDataDetails", action = "http://api.jasperwireless.com/ws/service/billing/GetTerminalUsageDataDetails")
    @WebResult(name = "GetTerminalUsageDataDetailsResponse", targetNamespace = "http://api.jasperwireless.com/ws/schema", partName = "body")
    public GetTerminalUsageDataDetailsResponse getTerminalUsageDataDetails(
        @WebParam(name = "GetTerminalUsageDataDetailsRequest", targetNamespace = "http://api.jasperwireless.com/ws/schema", partName = "body")
        GetTerminalUsageDataDetailsRequest body);

    /**
     * 
     * @param body
     * @return
     *     returns com.jasperwireless.api.ws.schema.GetTerminalUsageSmsDetailsResponse
     */
    @WebMethod(operationName = "GetTerminalUsageSmsDetails", action = "http://api.jasperwireless.com/ws/service/billing/GetTerminalUsageSmsDetails")
    @WebResult(name = "GetTerminalUsageSmsDetailsResponse", targetNamespace = "http://api.jasperwireless.com/ws/schema", partName = "body")
    public GetTerminalUsageSmsDetailsResponse getTerminalUsageSmsDetails(
        @WebParam(name = "GetTerminalUsageSmsDetailsRequest", targetNamespace = "http://api.jasperwireless.com/ws/schema", partName = "body")
        GetTerminalUsageSmsDetailsRequest body);

    /**
     * 
     * @param body
     * @return
     *     returns com.jasperwireless.api.ws.schema.GetTerminalUsageVoiceDetailsResponse
     */
    @WebMethod(operationName = "GetTerminalUsageVoiceDetails", action = "http://api.jasperwireless.com/ws/service/billing/GetTerminalUsageVoiceDetails")
    @WebResult(name = "GetTerminalUsageVoiceDetailsResponse", targetNamespace = "http://api.jasperwireless.com/ws/schema", partName = "body")
    public GetTerminalUsageVoiceDetailsResponse getTerminalUsageVoiceDetails(
        @WebParam(name = "GetTerminalUsageVoiceDetailsRequest", targetNamespace = "http://api.jasperwireless.com/ws/schema", partName = "body")
        GetTerminalUsageVoiceDetailsRequest body);

}
