
package com.jasperwireless.api.ws.schema;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 *
 */
@WebServiceClient(name = "EventPlanService", targetNamespace = "http://api.jasperwireless.com/ws/schema", wsdlLocation = "http://api.jasperwireless.com/ws/schema/Eventplan.wsdl")
public class EventPlanService
    extends Service
{

    private final static URL EVENTPLANSERVICE_WSDL_LOCATION;
    private final static WebServiceException EVENTPLANSERVICE_EXCEPTION;
    private final static QName EVENTPLANSERVICE_QNAME = new QName("http://api.jasperwireless.com/ws/schema", "EventPlanService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://api.jasperwireless.com/ws/schema/Eventplan.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        EVENTPLANSERVICE_WSDL_LOCATION = url;
        EVENTPLANSERVICE_EXCEPTION = e;
    }

    public EventPlanService() {
        super(__getWsdlLocation(), EVENTPLANSERVICE_QNAME);
    }

    public EventPlanService(WebServiceFeature... features) {
        super(__getWsdlLocation(), EVENTPLANSERVICE_QNAME, features);
    }

    public EventPlanService(URL wsdlLocation) {
        super(wsdlLocation, EVENTPLANSERVICE_QNAME);
    }

    public EventPlanService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, EVENTPLANSERVICE_QNAME, features);
    }

    public EventPlanService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EventPlanService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns EventPlanPortType
     */
    @WebEndpoint(name = "EventPlanPort")
    public EventPlanPortType getEventPlanPort() {
        return super.getPort(new QName("http://api.jasperwireless.com/ws/schema", "EventPlanPort"), EventPlanPortType.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EventPlanPortType
     */
    @WebEndpoint(name = "EventPlanPort")
    public EventPlanPortType getEventPlanPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://api.jasperwireless.com/ws/schema", "EventPlanPort"), EventPlanPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (EVENTPLANSERVICE_EXCEPTION!= null) {
            throw EVENTPLANSERVICE_EXCEPTION;
        }
        return EVENTPLANSERVICE_WSDL_LOCATION;
    }

}
