
package com.jasperwireless.api.ws.schema;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "EventPlanPortType", targetNamespace = "http://api.jasperwireless.com/ws/schema")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EventPlanPortType {


    /**
     * 
     * @param body
     * @return
     *     returns com.jasperwireless.api.ws.schema.GetAvailableEventsResponse
     */
    @WebMethod(operationName = "GetAvailableEvents", action = "http://api.jasperwireless.com/ws/service/eventplan/GetAvailableEvents")
    @WebResult(name = "GetAvailableEventsResponse", targetNamespace = "http://api.jasperwireless.com/ws/schema", partName = "body")
    public GetAvailableEventsResponse getAvailableEvents(
        @WebParam(name = "GetAvailableEventsRequest", targetNamespace = "http://api.jasperwireless.com/ws/schema", partName = "body")
        GetAvailableEventsRequest body);

    /**
     * 
     * @param body
     * @return
     *     returns com.jasperwireless.api.ws.schema.ActivateTerminalEventResponse
     */
    @WebMethod(operationName = "ActivateTerminalEvent", action = "http://api.jasperwireless.com/ws/service/eventplan/ActivateTerminalEvent")
    @WebResult(name = "ActivateTerminalEventResponse", targetNamespace = "http://api.jasperwireless.com/ws/schema", partName = "body")
    public ActivateTerminalEventResponse activateTerminalEvent(
        @WebParam(name = "ActivateTerminalEventRequest", targetNamespace = "http://api.jasperwireless.com/ws/schema", partName = "body")
        ActivateTerminalEventRequest body);

    /**
     * 
     * @param body
     * @return
     *     returns com.jasperwireless.api.ws.schema.GetTerminalEventsResponse
     */
    @WebMethod(operationName = "GetTerminalEvents", action = "http://api.jasperwireless.com/ws/service/eventplan/GetTerminalEvents")
    @WebResult(name = "GetTerminalEventsResponse", targetNamespace = "http://api.jasperwireless.com/ws/schema", partName = "body")
    public GetTerminalEventsResponse getTerminalEvents(
        @WebParam(name = "GetTerminalEventsRequest", targetNamespace = "http://api.jasperwireless.com/ws/schema", partName = "body")
        GetTerminalEventsRequest body);

    /**
     * 
     * @param body
     * @return
     *     returns com.jasperwireless.api.ws.schema.DeleteTerminalEventResponse
     */
    @WebMethod(operationName = "DeleteTerminalEvent", action = "http://api.jasperwireless.com/ws/service/eventplan/DeleteTerminalEvent")
    @WebResult(name = "DeleteTerminalEventResponse", targetNamespace = "http://api.jasperwireless.com/ws/schema", partName = "body")
    public DeleteTerminalEventResponse deleteTerminalEvent(
        @WebParam(name = "DeleteTerminalEventRequest", targetNamespace = "http://api.jasperwireless.com/ws/schema", partName = "body")
        DeleteTerminalEventRequest body);

}
