
package com.jasperwireless.api.ws.schema;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "GlobalSimTransferPortType", targetNamespace = "http://api.jasperwireless.com/ws/schema")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface GlobalSimTransferPortType {


    /**
     * 
     * @param body
     * @return
     *     returns com.jasperwireless.api.ws.schema.TransferGlobalSimResponse
     */
    @WebMethod(operationName = "TransferGlobalSim", action = "http://api.jasperwireless.com/ws/service/globalsimtransfer/TransferGlobalSim")
    @WebResult(name = "TransferGlobalSimResponse", targetNamespace = "http://api.jasperwireless.com/ws/schema", partName = "body")
    public TransferGlobalSimResponse transferGlobalSim(
        @WebParam(name = "TransferGlobalSimRequest", targetNamespace = "http://api.jasperwireless.com/ws/schema", partName = "body")
        TransferGlobalSimRequest body);

    /**
     * 
     * @param body
     * @return
     *     returns com.jasperwireless.api.ws.schema.GetGlobalSimTransferStatusResponse
     */
    @WebMethod(operationName = "GetGlobalSimTransferStatus", action = "http://api.jasperwireless.com/ws/service/globalsimtransfer/GetGlobalSimTransferStatus")
    @WebResult(name = "GetGlobalSimTransferStatusResponse", targetNamespace = "http://api.jasperwireless.com/ws/schema", partName = "body")
    public GetGlobalSimTransferStatusResponse getGlobalSimTransferStatus(
        @WebParam(name = "GetGlobalSimTransferStatusRequest", targetNamespace = "http://api.jasperwireless.com/ws/schema", partName = "body")
        GetGlobalSimTransferStatusRequest body);

    /**
     * 
     * @param body
     * @return
     *     returns com.jasperwireless.api.ws.schema.CancelGlobalSimTransferResponse
     */
    @WebMethod(operationName = "CancelGlobalSimTransfer", action = "http://api.jasperwireless.com/ws/service/globalsimtransfer/CancelGlobalSimTransfer")
    @WebResult(name = "CancelGlobalSimTransferResponse", targetNamespace = "http://api.jasperwireless.com/ws/schema", partName = "body")
    public CancelGlobalSimTransferResponse cancelGlobalSimTransfer(
        @WebParam(name = "CancelGlobalSimTransferRequest", targetNamespace = "http://api.jasperwireless.com/ws/schema", partName = "body")
        CancelGlobalSimTransferRequest body);

}
