
package com.jasperwireless.api.ws.schema;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "NetworkAccessService", targetNamespace = "http://api.jasperwireless.com/ws/schema", wsdlLocation = "file:/Users/calvernaz/sandbox/github-modules/jasperwireless-api/src/main/resources/NetworkAccess.wsdl")
public class NetworkAccessService
    extends Service
{

    private final static URL NETWORKACCESSSERVICE_WSDL_LOCATION;
    private final static WebServiceException NETWORKACCESSSERVICE_EXCEPTION;
    private final static QName NETWORKACCESSSERVICE_QNAME = new QName("http://api.jasperwireless.com/ws/schema", "NetworkAccessService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/Users/calvernaz/sandbox/github-modules/jasperwireless-api/src/main/resources/NetworkAccess.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        NETWORKACCESSSERVICE_WSDL_LOCATION = url;
        NETWORKACCESSSERVICE_EXCEPTION = e;
    }

    public NetworkAccessService() {
        super(__getWsdlLocation(), NETWORKACCESSSERVICE_QNAME);
    }

    public NetworkAccessService(WebServiceFeature... features) {
        super(__getWsdlLocation(), NETWORKACCESSSERVICE_QNAME, features);
    }

    public NetworkAccessService(URL wsdlLocation) {
        super(wsdlLocation, NETWORKACCESSSERVICE_QNAME);
    }

    public NetworkAccessService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, NETWORKACCESSSERVICE_QNAME, features);
    }

    public NetworkAccessService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public NetworkAccessService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns NetworkAccessPortType
     */
    @WebEndpoint(name = "NetworkAccessPort")
    public NetworkAccessPortType getNetworkAccessPort() {
        return super.getPort(new QName("http://api.jasperwireless.com/ws/schema", "NetworkAccessPort"), NetworkAccessPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns NetworkAccessPortType
     */
    @WebEndpoint(name = "NetworkAccessPort")
    public NetworkAccessPortType getNetworkAccessPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://api.jasperwireless.com/ws/schema", "NetworkAccessPort"), NetworkAccessPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (NETWORKACCESSSERVICE_EXCEPTION!= null) {
            throw NETWORKACCESSSERVICE_EXCEPTION;
        }
        return NETWORKACCESSSERVICE_WSDL_LOCATION;
    }

}
