
package com.jasperwireless.api.ws.schema;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "NetworkAccessPortType", targetNamespace = "http://api.jasperwireless.com/ws/schema")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface NetworkAccessPortType {


    /**
     * 
     * @param body
     * @return
     *     returns com.jasperwireless.api.ws.schema.EditNetworkAccessConfigResponse
     */
    @WebMethod(operationName = "EditNetworkAccessConfig", action = "http://api.jasperwireless.com/ws/service/networkaccess/EditNetworkAccessConfig")
    @WebResult(name = "EditNetworkAccessConfigResponse", targetNamespace = "http://api.jasperwireless.com/ws/schema", partName = "body")
    public EditNetworkAccessConfigResponse editNetworkAccessConfig(
        @WebParam(name = "EditNetworkAccessConfigRequest", targetNamespace = "http://api.jasperwireless.com/ws/schema", partName = "body")
        EditNetworkAccessConfigRequest body);

    /**
     * 
     * @param body
     * @return
     *     returns com.jasperwireless.api.ws.schema.GetNetworkAccessConfigResponse
     */
    @WebMethod(operationName = "GetNetworkAccessConfig", action = "http://api.jasperwireless.com/ws/service/networkaccess/GetNetworkAccessConfig")
    @WebResult(name = "GetNetworkAccessConfigResponse", targetNamespace = "http://api.jasperwireless.com/ws/schema", partName = "body")
    public GetNetworkAccessConfigResponse getNetworkAccessConfig(
        @WebParam(name = "GetNetworkAccessConfigRequest", targetNamespace = "http://api.jasperwireless.com/ws/schema", partName = "body")
        GetNetworkAccessConfigRequest body);

}
