
package com.jasperwireless.api.ws.schema;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SmsPortType", targetNamespace = "http://api.jasperwireless.com/ws/schema")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SmsPortType {


    /**
     * 
     * @param body
     * @return
     *     returns com.jasperwireless.api.ws.schema.GetSMSDetailsResponse
     */
    @WebMethod(operationName = "GetSMSDetails", action = "http://api.jasperwireless.com/ws/service/sms/GetSMSDetails")
    @WebResult(name = "GetSMSDetailsResponse", targetNamespace = "http://api.jasperwireless.com/ws/schema", partName = "body")
    public GetSMSDetailsResponse getSMSDetails(
        @WebParam(name = "GetSMSDetailsRequest", targetNamespace = "http://api.jasperwireless.com/ws/schema", partName = "body")
        GetSMSDetailsRequest body);

    /**
     * 
     * @param body
     * @return
     *     returns com.jasperwireless.api.ws.schema.GetModifiedSMSResponse
     */
    @WebMethod(operationName = "GetModifiedSMS", action = "http://api.jasperwireless.com/ws/service/sms/GetModifiedSMS")
    @WebResult(name = "GetModifiedSMSResponse", targetNamespace = "http://api.jasperwireless.com/ws/schema", partName = "body")
    public GetModifiedSMSResponse getModifiedSMS(
        @WebParam(name = "GetModifiedSMSRequest", targetNamespace = "http://api.jasperwireless.com/ws/schema", partName = "body")
        GetModifiedSMSRequest body);

    /**
     * 
     * @param body
     * @return
     *     returns com.jasperwireless.api.ws.schema.SendSMSResponse
     */
    @WebMethod(operationName = "SendSMS", action = "http://api.jasperwireless.com/ws/service/sms/SendSMS")
    @WebResult(name = "SendSMSResponse", targetNamespace = "http://api.jasperwireless.com/ws/schema", partName = "body")
    public SendSMSResponse sendSMS(
        @WebParam(name = "SendSMSRequest", targetNamespace = "http://api.jasperwireless.com/ws/schema", partName = "body")
        SendSMSRequest body);

    /**
     * 
     * @param body
     * @return
     *     returns com.jasperwireless.api.ws.schema.SendSMSToMsisdnResponse
     */
    @WebMethod(operationName = "SendSMSToMsisdn", action = "http://api.jasperwireless.com/ws/service/sms/SendSMSToMsisdn")
    @WebResult(name = "SendSMSToMsisdnResponse", targetNamespace = "http://api.jasperwireless.com/ws/schema", partName = "body")
    public SendSMSToMsisdnResponse sendSMSToMsisdn(
        @WebParam(name = "SendSMSToMsisdnRequest", targetNamespace = "http://api.jasperwireless.com/ws/schema", partName = "body")
        SendSMSToMsisdnRequest body);

    /**
     * 
     * @param body
     * @return
     *     returns com.jasperwireless.api.ws.schema.SendBulkSMSResponse
     */
    @WebMethod(operationName = "SendBulkSMS", action = "http://api.jasperwireless.com/ws/service/sms/SendBulkSMS")
    @WebResult(name = "SendBulkSMSResponse", targetNamespace = "http://api.jasperwireless.com/ws/schema", partName = "body")
    public SendBulkSMSResponse sendBulkSMS(
        @WebParam(name = "SendBulkSMSRequest", targetNamespace = "http://api.jasperwireless.com/ws/schema", partName = "body")
        SendBulkSMSRequest body);

    /**
     * 
     * @param body
     * @return
     *     returns com.jasperwireless.api.ws.schema.SendBulkSMSToMsisdnResponse
     */
    @WebMethod(operationName = "SendBulkSMSToMsisdn", action = "http://api.jasperwireless.com/ws/service/sms/SendBulkSMSToMsisdn")
    @WebResult(name = "SendBulkSMSToMsisdnResponse", targetNamespace = "http://api.jasperwireless.com/ws/schema", partName = "body")
    public SendBulkSMSToMsisdnResponse sendBulkSMSToMsisdn(
        @WebParam(name = "SendBulkSMSToMsisdnRequest", targetNamespace = "http://api.jasperwireless.com/ws/schema", partName = "body")
        SendBulkSMSToMsisdnRequest body);

}
