
package com.jasperwireless.api.ws.schema;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SmsService", targetNamespace = "http://api.jasperwireless.com/ws/schema", wsdlLocation = "file:/Users/calvernaz/sandbox/github-modules/jasperwireless-api/src/main/resources/Sms.wsdl")
public class SmsService
    extends Service
{

    private final static URL SMSSERVICE_WSDL_LOCATION;
    private final static WebServiceException SMSSERVICE_EXCEPTION;
    private final static QName SMSSERVICE_QNAME = new QName("http://api.jasperwireless.com/ws/schema", "SmsService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/Users/calvernaz/sandbox/github-modules/jasperwireless-api/src/main/resources/Sms.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SMSSERVICE_WSDL_LOCATION = url;
        SMSSERVICE_EXCEPTION = e;
    }

    public SmsService() {
        super(__getWsdlLocation(), SMSSERVICE_QNAME);
    }

    public SmsService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SMSSERVICE_QNAME, features);
    }

    public SmsService(URL wsdlLocation) {
        super(wsdlLocation, SMSSERVICE_QNAME);
    }

    public SmsService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SMSSERVICE_QNAME, features);
    }

    public SmsService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SmsService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SmsPortType
     */
    @WebEndpoint(name = "SmsPort")
    public SmsPortType getSmsPort() {
        return super.getPort(new QName("http://api.jasperwireless.com/ws/schema", "SmsPort"), SmsPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SmsPortType
     */
    @WebEndpoint(name = "SmsPort")
    public SmsPortType getSmsPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://api.jasperwireless.com/ws/schema", "SmsPort"), SmsPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SMSSERVICE_EXCEPTION!= null) {
            throw SMSSERVICE_EXCEPTION;
        }
        return SMSSERVICE_WSDL_LOCATION;
    }

}
