
package com.jasperwireless.api.ws.schema;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "TerminalPortType", targetNamespace = "http://api.jasperwireless.com/ws/schema")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TerminalPortType {


    /**
     * 
     * @param body
     * @return
     *     returns com.jasperwireless.api.ws.schema.EditTerminalResponse
     */
    @WebMethod(operationName = "EditTerminal", action = "http://api.jasperwireless.com/ws/service/terminal/EditTerminal")
    @WebResult(name = "EditTerminalResponse", targetNamespace = "http://api.jasperwireless.com/ws/schema", partName = "body")
    public EditTerminalResponse editTerminal(
        @WebParam(name = "EditTerminalRequest", targetNamespace = "http://api.jasperwireless.com/ws/schema", partName = "body")
        EditTerminalRequest body);

    /**
     * 
     * @param body
     * @return
     *     returns com.jasperwireless.api.ws.schema.EditTerminalRatingResponse
     */
    @WebMethod(operationName = "EditTerminalRating", action = "http://api.jasperwireless.com/ws/service/terminal/EditTerminalRating")
    @WebResult(name = "EditTerminalRatingResponse", targetNamespace = "http://api.jasperwireless.com/ws/schema", partName = "body")
    public EditTerminalRatingResponse editTerminalRating(
        @WebParam(name = "EditTerminalRatingRequest", targetNamespace = "http://api.jasperwireless.com/ws/schema", partName = "body")
        EditTerminalRatingRequest body);

    /**
     * 
     * @param body
     * @return
     *     returns com.jasperwireless.api.ws.schema.GetTerminalDetailsResponse
     */
    @WebMethod(operationName = "GetTerminalDetails", action = "http://api.jasperwireless.com/ws/service/terminal/GetTerminalDetails")
    @WebResult(name = "GetTerminalDetailsResponse", targetNamespace = "http://api.jasperwireless.com/ws/schema", partName = "body")
    public GetTerminalDetailsResponse getTerminalDetails(
        @WebParam(name = "GetTerminalDetailsRequest", targetNamespace = "http://api.jasperwireless.com/ws/schema", partName = "body")
        GetTerminalDetailsRequest body);

    /**
     * 
     * @param body
     * @return
     *     returns com.jasperwireless.api.ws.schema.GetLinePayStatusByOpAcctIdResponse
     */
    @WebMethod(operationName = "GetLinePayStatusByOpAcctId", action = "http://api.jasperwireless.com/ws/service/terminal/GetLinePayStatusByOpAcctId")
    @WebResult(name = "GetLinePayStatusByOpAcctIdResponse", targetNamespace = "http://api.jasperwireless.com/ws/schema", partName = "body")
    public GetLinePayStatusByOpAcctIdResponse getLinePayStatusByOpAcctId(
        @WebParam(name = "GetLinePayStatusByOpAcctIdRequest", targetNamespace = "http://api.jasperwireless.com/ws/schema", partName = "body")
        GetLinePayStatusByOpAcctIdRequest body);

    /**
     * 
     * @param body
     * @return
     *     returns com.jasperwireless.api.ws.schema.EditLinePayStatusResponse
     */
    @WebMethod(operationName = "EditLinePayStatus", action = "http://api.jasperwireless.com/ws/service/terminal/EditLinePayStatus")
    @WebResult(name = "EditLinePayStatusResponse", targetNamespace = "http://api.jasperwireless.com/ws/schema", partName = "body")
    public EditLinePayStatusResponse editLinePayStatus(
        @WebParam(name = "EditLinePayStatusRequest", targetNamespace = "http://api.jasperwireless.com/ws/schema", partName = "body")
        EditLinePayStatusRequest body);

    /**
     * 
     * @param body
     * @return
     *     returns com.jasperwireless.api.ws.schema.EditLinePayStatusPerAcctResponse
     */
    @WebMethod(operationName = "EditLinePayStatusPerAcct", action = "http://api.jasperwireless.com/ws/service/terminal/EditLinePayStatusPerAcct")
    @WebResult(name = "EditLinePayStatusPerAcctResponse", targetNamespace = "http://api.jasperwireless.com/ws/schema", partName = "body")
    public EditLinePayStatusPerAcctResponse editLinePayStatusPerAcct(
        @WebParam(name = "EditLinePayStatusPerAcctRequest", targetNamespace = "http://api.jasperwireless.com/ws/schema", partName = "body")
        EditLinePayStatusPerAcctRequest body);

    /**
     * 
     * @param body
     * @return
     *     returns com.jasperwireless.api.ws.schema.TransferTerminalAccountNoSimStatusResponse
     */
    @WebMethod(operationName = "TransferTerminalAccountNoSimStatus", action = "http://api.jasperwireless.com/ws/service/terminal/TransferTerminalAccountNoSimStatus")
    @WebResult(name = "TransferTerminalAccountNoSimStatusResponse", targetNamespace = "http://api.jasperwireless.com/ws/schema", partName = "body")
    public TransferTerminalAccountNoSimStatusResponse transferTerminalAccountNoSimStatus(
        @WebParam(name = "TransferTerminalAccountNoSimStatusRequest", targetNamespace = "http://api.jasperwireless.com/ws/schema", partName = "body")
        TransferTerminalAccountNoSimStatusRequest body);

    /**
     * 
     * @param body
     * @return
     *     returns com.jasperwireless.api.ws.schema.GetTerminalRatingResponse
     */
    @WebMethod(operationName = "GetTerminalRating", action = "http://api.jasperwireless.com/ws/service/terminal/GetTerminalRating")
    @WebResult(name = "GetTerminalRatingResponse", targetNamespace = "http://api.jasperwireless.com/ws/schema", partName = "body")
    public GetTerminalRatingResponse getTerminalRating(
        @WebParam(name = "GetTerminalRatingRequest", targetNamespace = "http://api.jasperwireless.com/ws/schema", partName = "body")
        GetTerminalRatingRequest body);

    /**
     * 
     * @param body
     * @return
     *     returns com.jasperwireless.api.ws.schema.QueueTerminalRatePlanResponse
     */
    @WebMethod(operationName = "QueueTerminalRatePlan", action = "http://api.jasperwireless.com/ws/service/terminal/QueueTerminalRatePlan")
    @WebResult(name = "QueueTerminalRatePlanResponse", targetNamespace = "http://api.jasperwireless.com/ws/schema", partName = "body")
    public QueueTerminalRatePlanResponse queueTerminalRatePlan(
        @WebParam(name = "QueueTerminalRatePlanRequest", targetNamespace = "http://api.jasperwireless.com/ws/schema", partName = "body")
        QueueTerminalRatePlanRequest body);

    /**
     * 
     * @param body
     * @return
     *     returns com.jasperwireless.api.ws.schema.RemoveRatePlanFromQueueResponse
     */
    @WebMethod(operationName = "RemoveRatePlanFromQueue", action = "http://api.jasperwireless.com/ws/service/terminal/RemoveRatePlanFromQueue")
    @WebResult(name = "RemoveRatePlanFromQueueResponse", targetNamespace = "http://api.jasperwireless.com/ws/schema", partName = "body")
    public RemoveRatePlanFromQueueResponse removeRatePlanFromQueue(
        @WebParam(name = "RemoveRatePlanFromQueueRequest", targetNamespace = "http://api.jasperwireless.com/ws/schema", partName = "body")
        RemoveRatePlanFromQueueRequest body);

    /**
     * 
     * @param body
     * @return
     *     returns com.jasperwireless.api.ws.schema.GetModifiedTerminalsResponse
     */
    @WebMethod(operationName = "GetModifiedTerminals", action = "http://api.jasperwireless.com/ws/service/terminal/GetModifiedTerminals")
    @WebResult(name = "GetModifiedTerminalsResponse", targetNamespace = "http://api.jasperwireless.com/ws/schema", partName = "body")
    public GetModifiedTerminalsResponse getModifiedTerminals(
        @WebParam(name = "GetModifiedTerminalsRequest", targetNamespace = "http://api.jasperwireless.com/ws/schema", partName = "body")
        GetModifiedTerminalsRequest body);

    /**
     * 
     * @param body
     * @return
     *     returns com.jasperwireless.api.ws.schema.GetTerminalsBySecureSimIdResponse
     */
    @WebMethod(operationName = "GetTerminalsBySecureSimId", action = "http://api.jasperwireless.com/ws/service/terminal/GetTerminalsBySecureSimId")
    @WebResult(name = "GetTerminalsBySecureSimIdResponse", targetNamespace = "http://api.jasperwireless.com/ws/schema", partName = "body")
    public GetTerminalsBySecureSimIdResponse getTerminalsBySecureSimId(
        @WebParam(name = "GetTerminalsBySecureSimIdRequest", targetNamespace = "http://api.jasperwireless.com/ws/schema", partName = "body")
        GetTerminalsBySecureSimIdRequest body);

    /**
     * 
     * @param body
     * @return
     *     returns com.jasperwireless.api.ws.schema.GetSessionInfoResponse
     */
    @WebMethod(operationName = "GetSessionInfo", action = "http://api.jasperwireless.com/ws/service/terminal/GetSessionInfo")
    @WebResult(name = "GetSessionInfoResponse", targetNamespace = "http://api.jasperwireless.com/ws/schema", partName = "body")
    public GetSessionInfoResponse getSessionInfo(
        @WebParam(name = "GetSessionInfoRequest", targetNamespace = "http://api.jasperwireless.com/ws/schema", partName = "body")
        GetSessionInfoRequest body);

    /**
     * 
     * @param body
     * @return
     *     returns com.jasperwireless.api.ws.schema.GetTerminalsByMsisdnResponse
     */
    @WebMethod(operationName = "GetTerminalsByMsisdn", action = "http://api.jasperwireless.com/ws/service/terminal/GetTerminalsByMsisdn")
    @WebResult(name = "GetTerminalsByMsisdnResponse", targetNamespace = "http://api.jasperwireless.com/ws/schema", partName = "body")
    public GetTerminalsByMsisdnResponse getTerminalsByMsisdn(
        @WebParam(name = "GetTerminalsByMsisdnRequest", targetNamespace = "http://api.jasperwireless.com/ws/schema", partName = "body")
        GetTerminalsByMsisdnRequest body);

    /**
     * 
     * @param body
     * @return
     *     returns com.jasperwireless.api.ws.schema.GetTerminalsByImsiResponse
     */
    @WebMethod(operationName = "GetTerminalsByImsi", action = "http://api.jasperwireless.com/ws/service/terminal/GetTerminalsByImsi")
    @WebResult(name = "GetTerminalsByImsiResponse", targetNamespace = "http://api.jasperwireless.com/ws/schema", partName = "body")
    public GetTerminalsByImsiResponse getTerminalsByImsi(
        @WebParam(name = "GetTerminalsByImsiRequest", targetNamespace = "http://api.jasperwireless.com/ws/schema", partName = "body")
        GetTerminalsByImsiRequest body);

    /**
     * 
     * @param body
     * @return
     *     returns com.jasperwireless.api.ws.schema.SimRmaExchangeResponse
     */
    @WebMethod(operationName = "SimRmaExchange", action = "http://api.jasperwireless.com/ws/service/terminal/SimRmaExchange")
    @WebResult(name = "SimRmaExchangeResponse", targetNamespace = "http://api.jasperwireless.com/ws/schema", partName = "body")
    public SimRmaExchangeResponse simRmaExchange(
        @WebParam(name = "SimRmaExchangeRequest", targetNamespace = "http://api.jasperwireless.com/ws/schema", partName = "body")
        SimRmaExchangeRequest body);

    /**
     * 
     * @param body
     * @return
     *     returns com.jasperwireless.api.ws.schema.UpdateSecureSimCredentialsResponse
     */
    @WebMethod(operationName = "UpdateSecureSimCredentials", action = "http://api.jasperwireless.com/ws/service/terminal/UpdateSecureSimCredentials")
    @WebResult(name = "UpdateSecureSimCredentialsResponse", targetNamespace = "http://api.jasperwireless.com/ws/schema", partName = "body")
    public UpdateSecureSimCredentialsResponse updateSecureSimCredentials(
        @WebParam(name = "UpdateSecureSimCredentialsRequest", targetNamespace = "http://api.jasperwireless.com/ws/schema", partName = "body")
        UpdateSecureSimCredentialsRequest body);

    /**
     * 
     * @param body
     * @return
     *     returns com.jasperwireless.api.ws.schema.TransferSimsToAccountResponse
     */
    @WebMethod(operationName = "TransferSimsToAccount", action = "http://api.jasperwireless.com/ws/service/terminal/TransferSimsToAccount")
    @WebResult(name = "TransferSimsToAccountResponse", targetNamespace = "http://api.jasperwireless.com/ws/schema", partName = "body")
    public TransferSimsToAccountResponse transferSimsToAccount(
        @WebParam(name = "TransferSimsToAccountRequest", targetNamespace = "http://api.jasperwireless.com/ws/schema", partName = "body")
        TransferSimsToAccountRequest body);

    /**
     * 
     * @param body
     * @return
     *     returns com.jasperwireless.api.ws.schema.TransferTrialSimsToAccountResponse
     */
    @WebMethod(operationName = "TransferTrialSimsToAccount", action = "http://api.jasperwireless.com/ws/service/terminal/TransferTrialSimsToAccount")
    @WebResult(name = "TransferTrialSimsToAccountResponse", targetNamespace = "http://api.jasperwireless.com/ws/schema", partName = "body")
    public TransferTrialSimsToAccountResponse transferTrialSimsToAccount(
        @WebParam(name = "TransferTrialSimsToAccountRequest", targetNamespace = "http://api.jasperwireless.com/ws/schema", partName = "body")
        TransferTrialSimsToAccountRequest body);

    /**
     * 
     * @param body
     * @return
     *     returns com.jasperwireless.api.ws.schema.AssignOrUpdateIPAddressResponse
     */
    @WebMethod(operationName = "AssignOrUpdateIPAddress", action = "http://api.jasperwireless.com/ws/service/terminal/AssignOrUpdateIPAddress")
    @WebResult(name = "AssignOrUpdateIPAddressResponse", targetNamespace = "http://api.jasperwireless.com/ws/schema", partName = "body")
    public AssignOrUpdateIPAddressResponse assignOrUpdateIPAddress(
        @WebParam(name = "AssignOrUpdateIPAddressRequest", targetNamespace = "http://api.jasperwireless.com/ws/schema", partName = "body")
        AssignOrUpdateIPAddressRequest body);

    /**
     * 
     * @param body
     * @return
     *     returns com.jasperwireless.api.ws.schema.GetTerminalLatestRegistrationResponse
     */
    @WebMethod(operationName = "GetTerminalLatestRegistration", action = "http://api.jasperwireless.com/ws/service/terminal/GetTerminalLatestRegistration")
    @WebResult(name = "GetTerminalLatestRegistrationResponse", targetNamespace = "http://api.jasperwireless.com/ws/schema", partName = "body")
    public GetTerminalLatestRegistrationResponse getTerminalLatestRegistration(
        @WebParam(name = "GetTerminalLatestRegistrationRequest", targetNamespace = "http://api.jasperwireless.com/ws/schema", partName = "body")
        GetTerminalLatestRegistrationRequest body);

    /**
     * 
     * @param body
     * @return
     *     returns com.jasperwireless.api.ws.schema.GetTerminalLatestNetworkRegistrationResponse
     */
    @WebMethod(operationName = "GetTerminalLatestNetworkRegistration", action = "http://api.jasperwireless.com/ws/service/terminal/GetTerminalLatestNetworkRegistration")
    @WebResult(name = "GetTerminalLatestNetworkRegistrationResponse", targetNamespace = "http://api.jasperwireless.com/ws/schema", partName = "body")
    public GetTerminalLatestNetworkRegistrationResponse getTerminalLatestNetworkRegistration(
        @WebParam(name = "GetTerminalLatestNetworkRegistrationRequest", targetNamespace = "http://api.jasperwireless.com/ws/schema", partName = "body")
        GetTerminalLatestNetworkRegistrationRequest body);

    /**
     * 
     * @param body
     * @return
     *     returns com.jasperwireless.api.ws.schema.GetTerminalAuditTrailResponse
     */
    @WebMethod(operationName = "GetTerminalAuditTrail", action = "http://api.jasperwireless.com/ws/service/terminal/GetTerminalAuditTrail")
    @WebResult(name = "GetTerminalAuditTrailResponse", targetNamespace = "http://api.jasperwireless.com/ws/schema", partName = "body")
    public GetTerminalAuditTrailResponse getTerminalAuditTrail(
        @WebParam(name = "GetTerminalAuditTrailRequest", targetNamespace = "http://api.jasperwireless.com/ws/schema", partName = "body")
        GetTerminalAuditTrailRequest body);

    /**
     * 
     * @param body
     * @return
     *     returns com.jasperwireless.api.ws.schema.SendCancelLocationResponse
     */
    @WebMethod(operationName = "SendCancelLocation", action = "http://api.jasperwireless.com/ws/service/terminal/SendCancelLocation")
    @WebResult(name = "SendCancelLocationResponse", targetNamespace = "http://api.jasperwireless.com/ws/schema", partName = "body")
    public SendCancelLocationResponse sendCancelLocation(
        @WebParam(name = "SendCancelLocationRequest", targetNamespace = "http://api.jasperwireless.com/ws/schema", partName = "body")
        SendCancelLocationRequest body);

}
